# Generated by Django 5.2.9 on 2026-04-04 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(help_text='Email of the person requesting data access', max_length=254, verbose_name='Requester Email')),
                ('requester_name', models.CharField(blank=True, help_text='Full name of the requester', max_length=255, verbose_name='Requester Name')),
                ('subject', models.CharField(help_text='Ticket subject/title', max_length=500, verbose_name='Subject')),
                ('description', models.TextField(blank=True, help_text='Additional details or notes for the request', verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed by Alvao'), ('failed', 'Submission Failed')], default='draft', max_length=20, verbose_name='Status')),
                ('alvao_ticket_id', models.CharField(blank=True, help_text='Ticket ID returned by Alvao after submission', max_length=100, null=True, verbose_name='Alvao Ticket ID')),
                ('alvao_response', models.JSONField(blank=True, help_text='Full response from Alvao API', null=True, verbose_name='Alvao Response')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Session key for tracking cart before submission', max_length=40, null=True, verbose_name='Session Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('requester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Ticket Request',
                'verbose_name_plural': 'Ticket Requests',
                'db_table': 'ticketing_ticket_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('dataset', 'Dataset'), ('dataclass', 'Data Class'), ('table', 'Database Table')], max_length=20, verbose_name='Item Type')),
                ('item_id', models.CharField(help_text='Primary key of the requested item', max_length=100, verbose_name='Item ID')),
                ('item_name', models.CharField(help_text='Display name of the requested item', max_length=255, verbose_name='Item Name')),
                ('item_description', models.TextField(blank=True, verbose_name='Item Description')),
                ('parent_dataset', models.CharField(blank=True, help_text='Parent dataset ID for dataclasses and tables', max_length=100, verbose_name='Parent Dataset')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('ticket_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ticketing.ticketrequest', verbose_name='Ticket Request')),
            ],
            options={
                'verbose_name': 'Ticket Request Item',
                'verbose_name_plural': 'Ticket Request Items',
                'db_table': 'ticketing_ticket_request_item',
                'ordering': ['added_at'],
                'unique_together': {('ticket_request', 'item_type', 'item_id')},
            },
        ),
    ]
