# Generated by Django 5.2.9 on 2026-03-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(help_text='Unique identifier / name for this agent', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'fair_genomes_agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, help_text='Contact e-mail address', max_length=255, null=True, verbose_name='Email')),
                ('contact_page', models.CharField(blank=True, help_text='URL of a web page that can be used to reach the contact', max_length=500, null=True, verbose_name='Contact Page')),
            ],
            options={
                'verbose_name': 'Contact Point',
                'verbose_name_plural': 'Contact Points',
                'db_table': 'fair_genomes_contact_point',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('name', models.CharField(help_text='Unique identifier for this catalog', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('applicable_legislation', models.CharField(help_text='Legal basis under which this catalog is published (mandatory per HealthDCAT-AP v6)', max_length=500, verbose_name='Applicable Legislation')),
                ('publisher', models.ForeignKey(blank=True, help_text='Agent responsible for making this catalog available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='fair_genomes.agent', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
                'db_table': 'fair_genomes_catalog',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_point',
            field=models.ForeignKey(blank=True, help_text='Contact information for this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='fair_genomes.contactpoint', verbose_name='Contact Point'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('name', models.CharField(help_text='Unique identifier for this dataset', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('theme', models.CharField(blank=True, help_text='dcat:theme — category from a controlled vocabulary', max_length=500, null=True, verbose_name='Theme')),
                ('license', models.CharField(blank=True, help_text='dct:license — URL or SPDX identifier', max_length=500, null=True, verbose_name='License')),
                ('conformed_to', models.CharField(blank=True, help_text='dct:conformsTo — standard / specification URI', max_length=500, null=True, verbose_name='Conforms To')),
                ('issued', models.DateTimeField(blank=True, help_text='dct:issued — date of first publication', null=True, verbose_name='Issued')),
                ('modified', models.DateTimeField(blank=True, help_text='dct:modified — date of last modification', null=True, verbose_name='Modified')),
                ('keyword', models.TextField(blank=True, help_text='dcat:keyword — comma-separated keywords', null=True, verbose_name='Keywords')),
                ('source', models.TextField(blank=True, help_text='dct:source — URI of the source dataset', null=True, verbose_name='Source')),
                ('creator', models.TextField(blank=True, help_text='dct:creator — name(s) of the dataset creator(s)', null=True, verbose_name='Creator')),
                ('rights_holder', models.TextField(blank=True, help_text='dct:rightsHolder', null=True, verbose_name='Rights Holder')),
                ('provenance', models.TextField(blank=True, help_text='dct:provenance', null=True, verbose_name='Provenance')),
                ('access_rights', models.CharField(help_text='dct:accessRights — controlled vocabulary URI (mandatory per HealthDCAT-AP v6)', max_length=500, verbose_name='Access Rights')),
                ('applicable_legislation', models.CharField(help_text='dct:applicableLegislation (mandatory per HealthDCAT-AP v6)', max_length=500, verbose_name='Applicable Legislation')),
                ('health_category', models.CharField(help_text='healthdcat:healthCategory (mandatory per HealthDCAT-AP v6)', max_length=500, verbose_name='Health Category')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='fair_genomes.catalog', verbose_name='Catalog')),
                ('contact_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='fair_genomes.contactpoint', verbose_name='Contact Point')),
                ('hdab', models.ForeignKey(help_text='healthdcat:hdab — Health Data Access Body responsible for this dataset (mandatory per HealthDCAT-AP v6)', on_delete=django.db.models.deletion.PROTECT, related_name='hdab_datasets', to='fair_genomes.agent', verbose_name='HDAB')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_datasets', to='fair_genomes.agent', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'fair_genomes_dataset',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('name', models.CharField(help_text='Unique identifier for this distribution', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('format', models.CharField(blank=True, help_text='dct:format — media type or format URI', max_length=100, null=True, verbose_name='Format')),
                ('conformed_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='Conforms To')),
                ('byte_size', models.IntegerField(blank=True, help_text='dcat:byteSize', null=True, verbose_name='Byte Size')),
                ('rights', models.CharField(blank=True, help_text='dct:rights', max_length=500, null=True, verbose_name='Rights')),
                ('issued', models.DateTimeField(blank=True, null=True, verbose_name='Issued')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified')),
                ('access_url', models.CharField(help_text='dcat:accessURL (mandatory per HealthDCAT-AP v6)', max_length=500, verbose_name='Access URL')),
                ('applicable_legislation', models.CharField(help_text='dct:applicableLegislation (mandatory per HealthDCAT-AP v6)', max_length=500, verbose_name='Applicable Legislation')),
                ('dataset_name', models.ForeignKey(db_column='dataset_name', help_text='Dataset this distribution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='fair_genomes.dataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
                'db_table': 'fair_genomes_distribution',
                'managed': True,
            },
        ),
    ]
