# Generated by Django 5.2.9 on 2026-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('inserted_by', models.CharField(blank=True, help_text='User who created this record', max_length=100, null=True, verbose_name='Inserted By')),
                ('inserted_on', models.DateTimeField(blank=True, help_text='Timestamp when record was created', null=True, verbose_name='Inserted On')),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=100, null=True, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(blank=True, help_text='Timestamp when record was last updated', null=True, verbose_name='Updated On')),
                ('personal_identifier', models.CharField(help_text='Unique identifier for the individual', max_length=255, primary_key=True, serialize=False, verbose_name='Personal Identifier')),
                ('year_of_birth', models.IntegerField(blank=True, db_index=True, help_text='Year the individual was born', null=True, verbose_name='Year of Birth')),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'db_table': 'fair_genomes_personal',
                'ordering': ['-inserted_on'],
                'indexes': [models.Index(fields=['year_of_birth'], name='idx_personal_yob'), models.Index(fields=['inserted_on'], name='idx_personal_inserted')],
            },
        ),
    ]
