# Generated by Django 5.2.9 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fair_genomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statdefinition',
            name='chart_type',
            field=models.CharField(
                choices=[('doughnut', 'Doughnut chart'), ('bar', 'Bar chart')],
                default='doughnut',
                help_text=(
                    'Initial chart view shown to users. Users can switch each chart on the '
                    'distribution page.'
                ),
                max_length=20,
                verbose_name='Default chart view',
            ),
        ),
    ]
