# Generated by Django 5.2.9 on 2026-01-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataclassList',
            fields=[
                ('data_class', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_content', models.CharField(blank=True, max_length=50, null=True)),
                ('data_confidentality', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=50, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('data_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('repository', models.CharField(blank=True, max_length=5, null=True)),
                ('complete', models.CharField(blank=True, max_length=5, null=True)),
                ('etl', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Data Class',
                'verbose_name_plural': 'Data Classes',
                'db_table': 'metadata"."dataclass_list',
                'ordering': ['data_class_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataclassTableSchemes',
            fields=[
                ('pk', models.CompositePrimaryKey('data_class', 'col_order', blank=True, editable=False, primary_key=True, serialize=False)),
                ('data_class', models.CharField(db_column='data_class', max_length=100)),
                ('col_order', models.SmallIntegerField()),
                ('col_var', models.CharField(blank=True, max_length=100, null=True)),
                ('col_name', models.CharField(blank=True, max_length=255, null=True)),
                ('col_description', models.TextField(blank=True, null=True)),
                ('col_var_r', models.CharField(blank=True, max_length=100, null=True)),
                ('col_transf_r', models.SmallIntegerField(blank=True, null=True)),
                ('datatype_r', models.CharField(blank=True, max_length=20, null=True)),
                ('possible_key', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('confidentality', models.SmallIntegerField(blank=True, null=True)),
                ('vocabulary', models.TextField(blank=True, null=True)),
                ('calculated', models.SmallIntegerField(blank=True, null=True)),
                ('madatory', models.SmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'metadata"."dataclass_table_schemes',
                'ordering': ['col_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetList',
            fields=[
                ('data_set', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_set_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('contributor', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('rights_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('complete', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'metadata"."dataset_list',
                'ordering': ['data_set_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasourceList',
            fields=[
                ('data_source', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data_source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'metadata"."datasource_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbTableList',
            fields=[
                ('db_layer', models.CharField(blank=True, max_length=50, null=True)),
                ('db_table', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('db_table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateField(blank=True, null=True)),
                ('datetime_last_modified', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Database Table',
                'verbose_name_plural': 'Database Tables',
                'db_table': 'metadata"."db_table_list',
                'ordering': ['db_table_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbTableSchemes',
            fields=[
                ('pk', models.CompositePrimaryKey('db_table', 'var', blank=True, editable=False, primary_key=True, serialize=False)),
                ('db_table', models.CharField(db_column='db_table', max_length=100)),
                ('var_order', models.SmallIntegerField(blank=True, null=True)),
                ('var', models.CharField(max_length=100)),
                ('key_db', models.CharField(blank=True, max_length=100, null=True)),
                ('type_db', models.CharField(blank=True, max_length=20, null=True)),
                ('type_r', models.CharField(blank=True, max_length=20, null=True)),
                ('var_name', models.CharField(blank=True, max_length=255, null=True)),
                ('var_description', models.TextField(blank=True, null=True)),
                ('vocabulary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metadata"."db_table_schemes',
                'ordering': ['var_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('inserted_by', models.CharField(blank=True, help_text='User who created this record', max_length=100, null=True, verbose_name='Inserted By')),
                ('inserted_on', models.DateTimeField(blank=True, help_text='Timestamp when record was created', null=True, verbose_name='Inserted On')),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=100, null=True, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(blank=True, help_text='Timestamp when record was last updated', null=True, verbose_name='Updated On')),
                ('personal_identifier', models.CharField(help_text='Unique identifier for the individual', max_length=255, primary_key=True, serialize=False, verbose_name='Personal Identifier')),
                ('year_of_birth', models.IntegerField(blank=True, db_index=True, help_text='Year the individual was born', null=True, verbose_name='Year of Birth')),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'db_table': 'fair_genomes_personal',
                'ordering': ['-inserted_on'],
                'indexes': [models.Index(fields=['year_of_birth'], name='idx_personal_yob'), models.Index(fields=['inserted_on'], name='idx_personal_inserted')],
            },
        ),
    ]
