-- Mock data for development
-- This replaces production data with sample records

INSERT INTO metadata.datasource_list (data_source, data_source_name, subject, description) VALUES
('DS001', 'Klinická databáze', 'Klinika, Demografie, Péče o pacienty', 'Klinické záznamy a pozorování pacientů'),
('DS002', 'Laboratorní systém', 'Laboratoř, Diagnostika, Testování', 'Výsledky laboratoří a objednávky vyšetření'),
('DS003', 'Radiologický PACS', 'Zobrazování, Diagnostika, Radiologie', 'Lékařské snímky a radiologické zprávy'),
('DS004', 'Lékárenský systém', 'Léky, Lékárna, Léčba', 'Předpisy léků a aplikace medikace'),
('DS005', 'Fakturační systém', 'Finance, Administrativa, Náhrady', 'Fakturace pacientů a pojišťovací data'),
('DS006', 'Emergency (ARO)', 'Emergency, Akutní péče, Třídění', 'Návštěvy pohotovosti a třídění pacientů'),
('DS007', 'Operační systém', 'Chirurgie, Perioperační, Anestezie', 'Operační výkony a chirurgické zákroky'),
('DS008', 'Patologická laboratoř', 'Patologie, Laboratoř, Diagnostika', 'Vzorky tkání a výsledky patologie'),
('DS009', 'Monitorování JIP', 'Intenzivní péče, JIP, Monitoring', 'Data monitorování jednotky intenzivní péče'),
('DS010', 'Onkologický registr', 'Onkologie, Rakovina, Léčba', 'Diagnózy a léčba onkologických onemocnění');

INSERT INTO metadata.dataset_list (data_source, data_set, data_set_name, subject, description, author, contributor, publisher, rights_holder, provenance, complete) VALUES
('DS001', 'DS001_D01', 'Demografie pacientů', 'Demografie, Administrativa, Péče o pacienty', 'Základní údaje o pacientech včetně věku, pohlaví, etnicity', 'Klinický tým', 'IT oddělení', 'Nemocnice', 'Klinické oddělení', 'EMR systém', 'Ano'),
('DS001', 'DS001_D02', 'Vitální funkce', 'Pozorování, Monitoring, Klinika', 'Měření vitálních funkcí: TK, teplota, puls, O2', 'Ošetřovatelský tým', 'IT oddělení', 'Nemocnice', 'Klinické oddělení', 'EMR systém', 'Ano'),
('DS001', 'DS001_D03', 'Diagnózy', 'Klinika, ICD-10, Stavy', 'Záznamy diagnóz pacientů s kódy ICD-10', 'Lékařský personál', 'IT oddělení', 'Nemocnice', 'Klinické oddělení', 'EMR systém', 'Ano'),
('DS001', 'DS001_D04', 'Alergie', 'Klinika, Bezpečnost, Nežádoucí účinky', 'Záznamy alergií a nežádoucích reakcí pacientů', 'Klinický tým', 'IT oddělení', 'Nemocnice', 'Klinické oddělení', 'EMR systém', 'Ano'),
('DS001', 'DS001_D05', 'Očkování', 'Klinika, Prevence, Veřejné zdraví', 'Historie očkování a imunizační záznamy', 'Klinický tým', 'IT oddělení', 'Nemocnice', 'Klinické oddělení', 'EMR systém', 'Ne'),
('DS002', 'DS002_D01', 'Objednávky vyšetření', 'Laboratoř, Objednávky, Diagnostika', 'Objednávky laboratorních vyšetření a žádanky', 'Laboratorní tým', 'IT oddělení', 'Nemocnice', 'Laboratoř', 'LIS systém', 'Ano'),
('DS002', 'DS002_D02', 'Výsledky vyšetření', 'Laboratoř, Výsledky, Diagnostika, Klinika', 'Výsledky laboratorních testů s referenčními rozsahy', 'Laboratorní tým', 'IT oddělení', 'Nemocnice', 'Laboratoř', 'LIS systém', 'Ano'),
('DS002', 'DS002_D03', 'Mikrobiologie', 'Laboratoř, Mikrobiologie, Infekční nemoci', 'Mikrobiologické kultury a citlivost na antibiotika', 'Laboratorní tým', 'IT oddělení', 'Nemocnice', 'Laboratoř', 'LIS systém', 'Ano'),
('DS003', 'DS003_D01', 'Zobrazovací studie', 'Radiologie, Zobrazování, DICOM, Diagnostika', 'Metadata radiologických snímků a DICOM hlavičky', 'Radiologický tým', 'IT oddělení', 'Nemocnice', 'Radiologie', 'PACS systém', 'Ano'),
('DS003', 'DS003_D02', 'Radiologické zprávy', 'Radiologie, Zprávy, Diagnostika, Klinika', 'Interpretační zprávy a nálezy z radiologie', 'Radiologický tým', 'IT oddělení', 'Nemocnice', 'Radiologie', 'RIS systém', 'Ne'),
('DS004', 'DS004_D01', 'Předpisy léků', 'Lékárna, Léky, Léčba, Objednávky', 'Předpisy a aplikace medikace', 'Lékárenský tým', 'IT oddělení', 'Nemocnice', 'Lékárna', 'Lékárenský systém', 'Ano'),
('DS004', 'DS004_D02', 'Historie medikace', 'Lékárna, Léky, Historie, Reconciliace', 'Historie medikace pacientů a reconciliace', 'Lékárenský tým', 'IT oddělení', 'Nemocnice', 'Lékárna', 'Lékárenský systém', 'Ano'),
('DS005', 'DS005_D01', 'Návštěvy pacientů', 'Fakturace, Finance, Administrativa, Návštěvy', 'Fakturační data návštěv a kontaktů s pacienty', 'Finanční tým', 'IT oddělení', 'Nemocnice', 'Finance', 'Fakturační systém', 'Ano'),
('DS005', 'DS005_D02', 'Pojistné nároky', 'Fakturace, Finance, Nároky, Úhrady', 'Data pojistných nároků a úhrad', 'Finanční tým', 'IT oddělení', 'Nemocnice', 'Finance', 'Fakturační systém', 'Ano'),
('DS006', 'DS006_D01', 'Návštěvy ARO', 'Emergency, Akutní péče, Třídění, Urgentní', 'Záznamy návštěv pohotovosti a třídění', 'Tým ARO', 'IT oddělení', 'Nemocnice', 'ARO', 'ARO systém', 'Ano'),
('DS006', 'DS006_D02', 'Výkony ARO', 'Emergency, Výkony, Akutní péče, Léčba', 'Výkony prováděné na pohotovosti', 'Tým ARO', 'IT oddělení', 'Nemocnice', 'ARO', 'ARO systém', 'Ano'),
('DS007', 'DS007_D01', 'Operační výkony', 'Chirurgie, Perioperační, Výkony, Operační sál', 'Operační výkony a chirurgické záznamy', 'Chirurgický tým', 'IT oddělení', 'Nemocnice', 'Chirurgie', 'Operační systém', 'Ano'),
('DS007', 'DS007_D02', 'Anesteziologické záznamy', 'Chirurgie, Anestezie, Perioperační, Monitoring', 'Záznamy anestezie a monitorování', 'Anesteziologický tým', 'IT oddělení', 'Nemocnice', 'Anesteziologie', 'Operační systém', 'Ano'),
('DS008', 'DS008_D01', 'Patologické zprávy', 'Patologie, Laboratoř, Diagnostika, Analýza tkání', 'Patologické zprávy a diagnózy tkání', 'Patologický tým', 'IT oddělení', 'Nemocnice', 'Patologie', 'Laboratorní systém', 'Ano'),
('DS008', 'DS008_D02', 'Cytologie', 'Patologie, Laboratoř, Screening, Diagnostika', 'Cytologické screeningy a výsledky', 'Patologický tým', 'IT oddělení', 'Nemocnice', 'Patologie', 'Laboratorní systém', 'Ne'),
('DS009', 'DS009_D01', 'Vitální funkce JIP', 'Intenzivní péče, JIP, Monitoring, Akutní péče', 'Kontinuální monitoring vitálních funkcí na JIP', 'Tým JIP', 'IT oddělení', 'Nemocnice', 'JIP', 'Monitorovací systém', 'Ano'),
('DS009', 'DS009_D02', 'Data ventilátorů', 'Intenzivní péče, JIP, Respirační, Monitoring', 'Parametry a nastavení umělé plicní ventilace', 'Tým JIP', 'IT oddělení', 'Nemocnice', 'JIP', 'Monitorovací systém', 'Ano'),
('DS010', 'DS010_D01', 'Onkologický registr', 'Onkologie, Rakovina, Registr, Nádorové komise', 'Diagnózy a staging onkologických onemocnění', 'Onkologický tým', 'IT oddělení', 'Nemocnice', 'Onkologie', 'Registrový systém', 'Ano'),
('DS010', 'DS010_D02', 'Léčebné plány', 'Onkologie, Rakovina, Léčba, Chemoterapie, Radioterapie', 'Protokoly chemoterapie a radioterapie', 'Onkologický tým', 'IT oddělení', 'Nemocnice', 'Onkologie', 'Registrový systém', 'Ne');

INSERT INTO metadata.dataclass_list (data_set, data_class, data_class_name, subject, description) VALUES
('DS001_D01', 'DC001', 'Pacient', 'Demografie, Administrativa, Hlavní data', 'Hlavní data pacienta s identifikátory'),
('DS001_D01', 'DC002', 'Adresa', 'Demografie, Kontakt, Geografické', 'Kontaktní údaje a adresa pacienta'),
('DS001_D01', 'DC003', 'Kontakt', 'Demografie, Komunikace', 'Telefon a emailové adresy'),
('DS001_D02', 'DC004', 'Vitální funkce', 'Pozorování, Monitoring, Klinika, Ošetřovatelství', 'Teplota, TK, puls, dechová frekvence, saturace O2'),
('DS001_D03', 'DC005', 'Diagnóza', 'Klinika, ICD-10, Stavy, Nemoc', 'Diagnózy kódované dle ICD-10 s daty'),
('DS001_D03', 'DC006', 'Seznam problémů', 'Klinika, Stavy, Chronická onemocnění', 'Aktivní a historické problémy pacienta'),
('DS001_D04', 'DC007', 'Alergie', 'Klinika, Bezpečnost, Nežádoucí účinky, Reakce', 'Lékové a environální alergie'),
('DS001_D05', 'DC008', 'Očkování', 'Klinika, Prevence, Veřejné zdraví, Vakciny', 'Záznamy o očkování s daty a typy'),
('DS002_D01', 'DC009', 'Objednávka vyšetření', 'Laboratoř, Objednávky, Diagnostika, Testování', 'Objednávky laboratorních testů a žádanky'),
('DS002_D02', 'DC010', 'Výsledek vyšetření', 'Laboratoř, Výsledky, Diagnostika, Klinická chemie', 'Výsledky testů s referenčními rozsahy'),
('DS002_D02', 'DC011', 'Panel vyšetření', 'Laboratoř, Výsledky, Diagnostika, Panel testů', 'Seskupené výsledky testů (KO, KP, atd)'),
('DS002_D03', 'DC012', 'Mikrobiologická kultivace', 'Laboratoř, Mikrobiologie, Infekční nemoci, Testování', 'Výsledky kulturačních vyšetření a identifikace organismů'),
('DS002_D03', 'DC013', 'Citlivost', 'Laboratoř, Mikrobiologie, Antibiotická rezistence, Testování', 'Testování citlivosti na antibiotika'),
('DS003_D01', 'DC014', 'Studie', 'Radiologie, Zobrazování, DICOM, Diagnostika, Lékařské zobrazování', 'Metadata zobrazovacích studií a DICOM informace'),
('DS003_D01', 'DC015', 'Série', 'Radiologie, Zobrazování, DICOM, Lékařské zobrazování', 'Série snímků v rámci studií'),
('DS003_D02', 'DC016', 'Zpráva', 'Radiologie, Zprávy, Diagnostika, Klinická dokumentace', 'Interpretační zprávy radiologů'),
('DS003_D02', 'DC017', 'Závěr', 'Radiologie, Zprávy, Nálezy, Klinika', 'Závěry a nálezy ze zpráv'),
('DS004_D01', 'DC018', 'Předpis', 'Lékárna, Léky, Objednávky, Léčba, Léková terapie', 'Objednávky léků a předpisy'),
('DS004_D01', 'DC019', 'Aplikace', 'Lékárna, Léky, Ošetřovatelství, MAR', 'Záznamy o aplikaci léků'),
('DS004_D02', 'DC020', 'Historie medikace', 'Lékárna, Léky, Historie, Reconciliace', 'Historické užívání léků'),
('DS005_D01', 'DC021', 'Návštěva', 'Fakturace, Finance, Návštěvy, Administrativa', 'Záznamy návštěv a kontaktů s pacienty'),
('DS005_D01', 'DC022', 'Poplatek', 'Fakturace, Finance, Příjmový cyklus, Výkony', 'Fakturační poplatky a výkony'),
('DS005_D02', 'DC023', 'Nárok', 'Fakturace, Finance, Pojištění, Zpracování nároků', 'Podání pojistných nároků'),
('DS005_D02', 'DC024', 'Platba', 'Fakturace, Finance, Úhrada, Příjmy', 'Záznamy plateb a úhrad'),
('DS006_D01', 'DC025', 'Návštěva ARO', 'Emergency, Akutní péče, Urgentní péče, Třídění', 'Detaily návštěv pohotovosti'),
('DS006_D01', 'DC026', 'Třídění', 'Emergency, Ošetřovatelství, Hodnocení, Náležitost', 'Hodnocení třídění a náležitosti na ARO'),
('DS006_D02', 'DC027', 'Výkon ARO', 'Emergency, Výkony, Léčba, Akutní péče', 'Výkony provedené na ARO'),
('DS007_D01', 'DC028', 'Operace', 'Chirurgie, Perioperační, Operační sál, Výkony', 'Detaily chirurgického výkonu'),
('DS007_D01', 'DC029', 'Operační protokol', 'Chirurgie, Dokumentace, Klinické záznamy, Operační sál', 'Chirurgické operační protokoly'),
('DS007_D02', 'DC030', 'Anestezie', 'Chirurgie, Anestezie, Perioperační, Monitoring', 'Záznamy anestezie a monitorování'),
('DS008_D01', 'DC031', 'Patologická zpráva', 'Patologie, Laboratoř, Diagnostika, Analýza tkání, Biopsie', 'Patologické zprávy tkání'),
('DS008_D01', 'DC032', 'Vzorek', 'Patologie, Laboratoř, Správa vzorků, Tkáň', 'Detaily vzorků tkání'),
('DS008_D02', 'DC033', 'Cytologie', 'Patologie, Laboratoř, Screening, Detekce rakoviny', 'Výsledky cytologického screeningu'),
('DS009_D01', 'DC034', 'Vitální funkce JIP', 'Intenzivní péče, JIP, Monitoring, Akutní péče', 'Kontinuální monitorování vitálních funkcí na JIP'),
('DS009_D01', 'DC035', 'Monitorovací list JIP', 'Intenzivní péče, JIP, Ošetřovatelství, Dokumentace', 'Ošetřovatelské monitorovací listy JIP'),
('DS009_D02', 'DC036', 'Ventilátor', 'Intenzivní péče, JIP, Respirační, Životní podpora', 'Data umělé plicní ventilace'),
('DS010_D01', 'DC037', 'Onkologická diagnóza', 'Onkologie, Rakovina, Nádorová komise, Nemoc', 'Diagnóza rakoviny a staging'),
('DS010_D01', 'DC038', 'Nádorový registr', 'Onkologie, Rakovina, Registr, Epidemiologie', 'Charakteristika nádorů a registrace'),
('DS010_D02', 'DC039', 'Chemoterapeutický protokol', 'Onkologie, Rakovina, Léčba, Chemoterapie, Léková terapie', 'Léčebné plány chemoterapie'),
('DS010_D02', 'DC040', 'Radioterapeutický plán', 'Onkologie, Rakovina, Léčba, Radioterapie, Ožarování', 'Protokoly radioterapie');

INSERT INTO metadata.db_table_list (data_class, db_layer, db_table, db_table_name, description) VALUES
('DC001', 'clinical', 'TBL_PATIENTS', 'Hlavní tabulka pacientů', 'Demografie a identifikace pacientů'),
('DC002', 'clinical', 'TBL_ADDRESSES', 'Adresy pacientů', 'Kontaktní informace pacientů'),
('DC003', 'clinical', 'TBL_CONTACTS', 'Kontaktní údaje', 'Telefonní čísla a emailové adresy'),
('DC004', 'clinical', 'TBL_VITAL_SIGNS', 'Vitální funkce', 'Měření vitálních funkcí pacienta'),
('DC005', 'clinical', 'TBL_DIAGNOSES', 'Diagnózy', 'Záznamy diagnóz pacientů'),
('DC006', 'clinical', 'TBL_PROBLEMS', 'Seznam problémů', 'Aktivní problémy pacienta'),
('DC007', 'clinical', 'TBL_ALLERGIES', 'Alergie', 'Alergie pacienta a reakce'),
('DC008', 'clinical', 'TBL_IMMUNIZATIONS', 'Očkování', 'Záznamy o očkování'),
('DC009', 'lab', 'TBL_LAB_ORDERS', 'Objednávky vyšetření', 'Objednávky laboratorních testů'),
('DC010', 'lab', 'TBL_LAB_RESULTS', 'Výsledky vyšetření', 'Výsledky laboratorních testů'),
('DC011', 'lab', 'TBL_LAB_PANELS', 'Panely vyšetření', 'Seskupené výsledky testů'),
('DC012', 'lab', 'TBL_CULTURES', 'Kultivace', 'Mikrobiologické kultivace'),
('DC013', 'lab', 'TBL_SENSITIVITY', 'Citlivost', 'Citlivost na antibiotika'),
('DC014', 'imaging', 'TBL_STUDIES', 'Zobrazovací studie', 'Metadata radiologických studií'),
('DC015', 'imaging', 'TBL_SERIES', 'Série snímků', 'Data sérií snímků'),
('DC016', 'imaging', 'TBL_REPORTS', 'Radiologické zprávy', 'Radiologické interpretace'),
('DC017', 'imaging', 'TBL_IMPRESSIONS', 'Závěry', 'Nálezy ze zpráv'),
('DC018', 'pharmacy', 'TBL_PRESCRIPTIONS', 'Předpisy', 'Předpisy léků'),
('DC019', 'pharmacy', 'TBL_MED_ADMIN', 'Aplikace léků', 'Aplikace medikace'),
('DC020', 'pharmacy', 'TBL_MED_HISTORY', 'Historie medikace', 'Historie medikace'),
('DC021', 'billing', 'TBL_ENCOUNTERS', 'Návštěvy', 'Návštěvy pacientů'),
('DC022', 'billing', 'TBL_CHARGES', 'Poplatky', 'Fakturační poplatky'),
('DC023', 'billing', 'TBL_CLAIMS', 'Nároky', 'Pojistné nároky'),
('DC024', 'billing', 'TBL_PAYMENTS', 'Platby', 'Záznamy plateb'),
('DC025', 'emergency', 'TBL_ED_VISITS', 'Návštěvy ARO', 'Návštěvy pohotovosti'),
('DC026', 'emergency', 'TBL_TRIAGE', 'Třídění', 'Data třídění ARO'),
('DC027', 'emergency', 'TBL_ED_PROCEDURES', 'Výkony ARO', 'Výkony na ARO'),
('DC028', 'surgical', 'TBL_SURGERIES', 'Operace', 'Chirurgické výkony'),
('DC029', 'surgical', 'TBL_OP_NOTES', 'Operační protokoly', 'Chirurgické záznamy'),
('DC030', 'surgical', 'TBL_ANESTHESIA', 'Anestezie', 'Záznamy anestezie'),
('DC031', 'pathology', 'TBL_PATH_REPORTS', 'Patologické zprávy', 'Patologie tkání'),
('DC032', 'pathology', 'TBL_SPECIMENS', 'Vzorky', 'Vzorky tkání'),
('DC033', 'pathology', 'TBL_CYTOLOGY', 'Cytologie', 'Výsledky cytologie'),
('DC034', 'icu', 'TBL_ICU_VITALS', 'Vitální funkce JIP', 'Monitoring vitálních funkcí JIP'),
('DC035', 'icu', 'TBL_FLOW_SHEETS', 'Monitorovací listy', 'Monitorovací listy JIP'),
('DC036', 'icu', 'TBL_VENTILATOR', 'Ventilátor', 'Data ventilátorů'),
('DC037', 'oncology', 'TBL_CANCER_DX', 'Onkologická diagnóza', 'Onkologické diagnózy'),
('DC038', 'oncology', 'TBL_TUMOR_REGISTRY', 'Nádorový registr', 'Registrace nádorů'),
('DC039', 'oncology', 'TBL_CHEMO', 'Chemoterapie', 'Protokoly chemoterapie'),
('DC040', 'oncology', 'TBL_RADIATION', 'Radioterapie', 'Radioterapie');

INSERT INTO metadata.db_table_schemes (db_table, var_order, var, type_db, var_name, var_description) VALUES
('TBL_PATIENTS', 1, 'patient_id', 'integer', 'ID pacienta', 'Unikátní identifikátor pacienta'),
('TBL_PATIENTS', 2, 'first_name', 'varchar', 'Křestní jméno', 'Křestní jméno pacienta'),
('TBL_PATIENTS', 3, 'last_name', 'varchar', 'Příjmení', 'Příjmení pacienta'),
('TBL_PATIENTS', 4, 'date_of_birth', 'date', 'Datum narození', 'Datum narození pacienta'),
('TBL_PATIENTS', 5, 'gender', 'varchar', 'Pohlaví', 'Pohlaví pacienta'),
('TBL_ADDRESSES', 1, 'address_id', 'integer', 'ID adresy', 'Unikátní identifikátor adresy'),
('TBL_ADDRESSES', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_ADDRESSES', 3, 'street', 'varchar', 'Ulice', 'Ulice'),
('TBL_ADDRESSES', 4, 'city', 'varchar', 'Město', 'Název města'),
('TBL_ADDRESSES', 5, 'postal_code', 'varchar', 'PSČ', 'Poštovní směrovací číslo'),
('TBL_VITAL_SIGNS', 1, 'vital_id', 'integer', 'ID záznamu', 'Unikátní záznam vitálních funkcí'),
('TBL_VITAL_SIGNS', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_VITAL_SIGNS', 3, 'measurement_time', 'timestamp', 'Čas', 'Časová značka měření'),
('TBL_VITAL_SIGNS', 4, 'temperature', 'numeric', 'Teplota', 'Tělesná teplota (°C)'),
('TBL_VITAL_SIGNS', 5, 'blood_pressure_sys', 'integer', 'TK systolický', 'Systolický krevní tlak'),
('TBL_VITAL_SIGNS', 6, 'blood_pressure_dia', 'integer', 'TK diastolický', 'Diastolický krevní tlak'),
('TBL_VITAL_SIGNS', 7, 'pulse', 'integer', 'Puls', 'Srdeční frekvence (tepy/min)'),
('TBL_DIAGNOSES', 1, 'diagnosis_id', 'integer', 'ID diagnózy', 'Unikátní záznam diagnózy'),
('TBL_DIAGNOSES', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_DIAGNOSES', 3, 'icd10_code', 'varchar', 'ICD-10', 'Kód diagnózy ICD-10'),
('TBL_DIAGNOSES', 4, 'diagnosis_date', 'date', 'Datum', 'Datum diagnózy'),
('TBL_LAB_ORDERS', 1, 'order_id', 'integer', 'ID objednávky', 'Unikátní identifikátor objednávky'),
('TBL_LAB_ORDERS', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_LAB_ORDERS', 3, 'test_code', 'varchar', 'Kód testu', 'Kód laboratorního testu'),
('TBL_LAB_ORDERS', 4, 'order_date', 'timestamp', 'Datum objednávky', 'Kdy byl test objednán'),
('TBL_LAB_RESULTS', 1, 'result_id', 'integer', 'ID výsledku', 'Unikátní identifikátor výsledku'),
('TBL_LAB_RESULTS', 2, 'order_id', 'integer', 'ID objednávky', 'Odkaz na objednávku'),
('TBL_LAB_RESULTS', 3, 'result_value', 'varchar', 'Hodnota', 'Hodnota výsledku testu'),
('TBL_LAB_RESULTS', 4, 'result_date', 'timestamp', 'Datum výsledku', 'Kdy je výsledek dostupný'),
('TBL_STUDIES', 1, 'study_id', 'integer', 'ID studie', 'Unikátní identifikátor studie'),
('TBL_STUDIES', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_STUDIES', 3, 'modality', 'varchar', 'Modalita', 'Typ zobrazování (CT, MRI, atd)'),
('TBL_STUDIES', 4, 'study_date', 'date', 'Datum studie', 'Datum zobrazovací studie'),
('TBL_REPORTS', 1, 'report_id', 'integer', 'ID zprávy', 'Unikátní identifikátor zprávy'),
('TBL_REPORTS', 2, 'study_id', 'integer', 'ID studie', 'Odkaz na studii'),
('TBL_REPORTS', 3, 'report_text', 'text', 'Zpráva', 'Text radiologické zprávy'),
('TBL_PRESCRIPTIONS', 1, 'prescription_id', 'integer', 'ID předpisu', 'Unikátní identifikátor předpisu'),
('TBL_PRESCRIPTIONS', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_PRESCRIPTIONS', 3, 'medication_name', 'varchar', 'Lék', 'Název léku'),
('TBL_PRESCRIPTIONS', 4, 'dosage', 'varchar', 'Dávkování', 'Předepsané dávkování'),
('TBL_ENCOUNTERS', 1, 'encounter_id', 'integer', 'ID návštěvy', 'Unikátní identifikátor návštěvy'),
('TBL_ENCOUNTERS', 2, 'patient_id', 'integer', 'ID pacienta', 'Odkaz na pacienta'),
('TBL_ENCOUNTERS', 3, 'encounter_date', 'date', 'Datum', 'Datum návštěvy'),
('TBL_ENCOUNTERS', 4, 'encounter_type', 'varchar', 'Typ', 'Typ návštěvy');
