# Generated by Django 5.2.9 on 2026-03-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Short machine-readable identifier, e.g. "v6".', unique=True, verbose_name='Slug')),
                ('label', models.CharField(help_text='Human-readable version label, e.g. "Health DCAT-AP v6".', max_length=200, verbose_name='Label')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active schema version used by the service layer.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Schema Version',
                'verbose_name_plural': 'Schema Versions',
                'db_table': 'schema_registry_version',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SchemaTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_key', models.SlugField(help_text='Stable snake_case identifier used in gettext msgids and binding references.', max_length=100, verbose_name='Term Key')),
                ('semantics', models.CharField(db_index=True, help_text='Prefixed name, e.g. "dct:identifier".', max_length=200, verbose_name='Semantics')),
                ('prefix', models.CharField(help_text='Namespace prefix extracted from semantics for convenience.', max_length=50, verbose_name='Prefix')),
                ('local_name', models.CharField(help_text='Local name extracted from semantics for convenience.', max_length=200, verbose_name='Local Name')),
                ('uri', models.CharField(help_text='Full URI constructed from prefix base + local_name.', max_length=500, verbose_name='URI')),
                ('base_label_en', models.CharField(help_text='English base label; used as gettext fallback.', max_length=200, verbose_name='Label (EN)')),
                ('base_description_en', models.TextField(help_text='English base description; used as gettext fallback.', verbose_name='Description (EN)')),
                ('requirement', models.CharField(choices=[('optional', 'Optional'), ('recommended', 'Recommended'), ('mandatory', 'Mandatory'), ('deprecated', 'Deprecated')], default='optional', help_text='Requirement level per the HealthDCAT-AP specification.', max_length=20, verbose_name='Requirement')),
                ('levels', models.JSONField(default=list, help_text='List of table/entity names where this term is applicable, e.g. ["Catalog","Dataset"].', verbose_name='Levels')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order in which terms are listed within a schema version.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schema_registry.schemaversion', verbose_name='Schema Version')),
            ],
            options={
                'verbose_name': 'Schema Term',
                'verbose_name_plural': 'Schema Terms',
                'db_table': 'schema_registry_term',
                'ordering': ['display_order', 'term_key'],
                'managed': True,
                'unique_together': {('schema_version', 'term_key')},
            },
        ),
        migrations.CreateModel(
            name='SchemaPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Namespace prefix, e.g. "dct".', max_length=50, verbose_name='Prefix')),
                ('base_uri', models.CharField(help_text='Full namespace URI corresponding to the prefix, e.g. "http://purl.org/dc/terms/".', max_length=500, verbose_name='Base URI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='schema_registry.schemaversion', verbose_name='Schema Version')),
            ],
            options={
                'verbose_name': 'Schema Prefix',
                'verbose_name_plural': 'Schema Prefixes',
                'db_table': 'schema_registry_prefix',
                'ordering': ['prefix'],
                'managed': True,
                'unique_together': {('schema_version', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='SchemaFieldBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='Name of the data model table/entity this binding belongs to.', max_length=100, verbose_name='Table Name')),
                ('column_name', models.CharField(blank=True, help_text='Physical column name; NULL for entity (table-level) bindings.', max_length=100, null=True, verbose_name='Column Name')),
                ('column_type', models.CharField(blank=True, help_text='Logical data type (string, text, integer, datetime, ref); NULL for entity rows.', max_length=50, null=True, verbose_name='Column Type')),
                ('ref_table', models.CharField(blank=True, help_text='Target entity name for FK-like columns, e.g. "Agent".', max_length=100, null=True, verbose_name='Ref Table')),
                ('label_en', models.CharField(help_text='English label for this binding; may differ from the term label in context.', max_length=200, verbose_name='Label (EN)')),
                ('description_en', models.TextField(help_text='English description for this binding.', verbose_name='Description (EN)')),
                ('is_entity', models.BooleanField(default=False, help_text='True for table-level (entity) rows; False for column-level rows.', verbose_name='Is Entity')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order in which bindings are listed within a table.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('schema_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='schema_registry.schematerm', verbose_name='Schema Term')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='schema_registry.schemaversion', verbose_name='Schema Version')),
            ],
            options={
                'verbose_name': 'Schema Field Binding',
                'verbose_name_plural': 'Schema Field Bindings',
                'db_table': 'schema_registry_field_binding',
                'ordering': ['table_name', 'display_order'],
                'managed': True,
                'unique_together': {('schema_version', 'table_name', 'column_name')},
            },
        ),
    ]
